# Generated by Django 2.2.17 on 2020-12-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=200)),
                ('f2', models.CharField(max_length=200)),
                ('f3', models.CharField(max_length=200)),
                ('f4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tabletwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=200)),
                ('c2', models.CharField(max_length=200)),
                ('c3', models.CharField(max_length=200)),
                ('c4', models.CharField(max_length=200)),
            ],
        ),
    ]
